---
- name: Adicionar chave GPG do repositório Grafana
  apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present


- name: Adicionar repositório Grafana
  apt_repository:
    repo: 'deb https://packages.grafana.com/oss/deb stable main'
    state: present
    update_cache: yes

- name: Instalar Grafana
  apt:
    name: grafana
    state: present
    update_cache: yes
...
